---

- name: Add discourse group
  group: name=discourse state=present

- name: Make sure the users are present
  user: name={{ item.name }} uid={{ item.uid }} home={{ item.home }} shell={{ item.shell }} comment="{{ item.comment }}" group={{ item.group }} groups={{ ",".join(item.groups) }} append={{ item.append }}
  with_items: $users

- name: Templated ~/.gemrc
  template: src=gemrc.j2 dest=/home/{{ discourse.user }}/.gemrc owner={{ discourse.user }} group={{ discourse.user }}

- name: Create Discourse location
  file: path={{ discourse.path }} owner={{ discourse.user }} group={{ discourse.user }} mode=0755 state=directory