- hosts: vagrant
  remote_user: "{{ user }}"
  sudo: yes
  roles:
    - ansible
    - vagrant
    - utilities

- hosts: discourse:&development
  remote_user: "{{ user }}"
  sudo: yes
  roles:
    - discourse

- hosts: gollum:&development
  remote_user: "{{ user }}"
  sudo: yes
  roles:
    - gollum
