---

- name: Add Redis PPA
  apt_repository: repo='ppa:rwky/redis' state=present

- name: Add nginx.org key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add nginx.org repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx' state=present

- name: apt-get update and upgrade
  apt: update_cache=yes upgrade=yes

- name: Install all packages from vars
  apt: pkg={{ item }} state=present
  with_items:
    - ${apt.base}

- name: Remove any nginx packages to install our own
  apt: pkg='^nginx.*$' state=absent