---

- name: install bluepill gem (gem for idempotency?)
  command: /home/${discourse.user}/.rvm/bin/gem install bluepill creates=/home/${discourse.user}/.rvm/gems/ruby-${ruby.global}/bin/bluepill
  tags: bluepill

- name: rvm wrappers for booting bluepill
  command: /home/${discourse.user}/.rvm/bin/rvm wrapper ${ruby.global} bootup bluepill chdir={{ discourse.path }}

- name: rvm wrappers for booting bundle
  command: /home/${discourse.user}/.rvm/bin/rvm wrapper ${ruby.global} bootup bundle chdir={{ discourse.path }}

- name: add bluepill alias to discourse user
  lineinfile: dest=/home/{{ discourse.user }}/.bash_aliases create=yes regexp="^alias bluepill" line='alias bluepill="NOEXEC_DISABLE=1 bluepill --no-privileged -c ~/.bluepill"'
  tags: bluepill


#- name: copy shims in to satisfy legacy RVM weirdness
  #template: src={{ item.src }} dest=/home/{{ discourse.user }}/.rbenv/shims/{{ item.dest }} mode=0755
  #with_items:
    #- { src: 'bootup_bundle.j2', dest: 'bootup_bundle' }
    #- { src: 'bootup_bluepill.j2', dest: 'bootup_bluepill' }
  #tags: bluepill
