---

- name: git clone discourse
  git: repo=git://github.com/discourse/discourse.git dest={{ discourse.path }} version=${discourse.version}
  register: git_cloned

- name: install gems for discourse (bundler for idempotency - first run is only long process)
  shell: /home/${discourse.user}/.rbenv/shims/bundle install --deployment --without test chdir={{ discourse.path }}

- name: install templates
  template: src={{ item.src }} dest={{ discourse.path }}/{{ item.dest }}
  with_items:
    - { src: 'database.yml.j2', dest: 'config/database.yml' }
    - { src: 'redis.yml.j2', dest: 'config/redis.yml' }
    - { src: 'discourse.pill.j2', dest: 'config/discourse.pill' }
    - { src: 'production.rb.j2', dest: 'config/environments/production.rb' }

- name: initialize database from project dir (relies on rake for idempotency)
  shell: RUBY_GC_MALLOC_LIMIT={{ ruby.gc_malloc_limit }} RAILS_ENV=production /home/{{ discourse.user }}/.rbenv/shims/bundle exec rake db:migrate chdir={{ discourse.path }}

- name: precompile assets
  shell: RUBY_GC_MALLOC_LIMIT={{ ruby.gc_malloc_limit }} RAILS_ENV=production /home/{{ discourse.user }}/.rbenv/shims/bundle exec rake assets:precompile chdir={{ discourse.path }}