---

- name: install postgres packages
  apt: package={{ item }} state=present
  with_items: ${postgres.aptpackage}

- name: start postgres becuase of handler issues
  service: name=postgresql state=started

- name: create discourse postgres user (needs to lock down attributes / best practices)
  postgresql_user: user={{ discourse.user }} password={{ discourse.prod.dbpasswd }} role_attr_flags=SUPERUSER
  sudo_user: postgres
  notify: reload postgres

- name: create discourse db
  postgresql_db: name={{ discourse.prod.db }} 
    encoding='UTF-8' lc_collate="en_US.utf8" lc_ctype="en_US.utf8" template='template0' owner={{ discourse.user }}
  sudo_user: postgres
  notify: reload postgres
