---

- name: Start up discourse
  command: /home/${discourse.user}/.rvm/bin/rvm ${ruby.global} exec bluepill --no-privileged -c /home/${discourse.user}/.bluepill load ${discourse.path}/config/discourse.pill chdir={{ discourse.path }}
  environment:
    RAILS_ENV: production
    RAILS_ROOT: "{{ discourse.path }}"
    NUM_WEBS: 2
    RUBY_GC_MALLOC_LIMIT: "{{ ruby.gc_malloc_limit }}"

- cron: name="discourse" 
        special_time=reboot 
        job="RUBY_GC_MALLOC_LIMIT=${ruby.gc_malloc_limit} RAILS_ROOT=${discourse.path} RAILS_ENV=production NUM_WEBS=2 /home/${discourse.user}/.rvm/bin/bootup_bluepill --no-privileged -c /home/${discourse.user}/.bluepill load ${discourse.path}/config/discourse.pill"
