---

- name: Add Redis PPA
  apt_repository: repo=ppa:rwky/redis state=present
  notify: update apt-cache

- name: Install redis-server
  apt: pkg=redis-server state=latest

- name: Ensure redis is started
  service: name=redis-server state=started