### Install Prerequisite packages

- name: Install Common useful utilities
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    # extra command-line utils not installed by default
    - htop
    - sysstat
    - iotop
    - iptraf
    - nethogs
    - iftop
    - traceroute
    - ptop

